FROM golang:1.25-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app

COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]





# # Stage 1: Build
# FROM golang:1.25-alpine AS builder
# #RUN apk add --no-cache git
# RUN apk update && apk add --no-cache git
# WORKDIR /app
# #COPY . .
# #COPY go.mod go.sum ./
# COPY MuchToDo/go.mod MuchToDo/go.sum* ./
# RUN go mod download
# #COPY MuchToDo/ .
# COPY MuchToDo/cmd ./cmd
# COPY MuchToDo/internal ./internal
# COPY MuchToDo/docs ./docs

# #COPY MuchToDo/pkg ./pkg  

# RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api

# # Stage 2: Final Image
# #check
# FROM alpine:latest
# RUN apk --no-cache add ca-certificates

# WORKDIR /root/

# COPY --from=builder /app/main .
# EXPOSE 8080
# CMD ["./main"]